#!/bin/sh
if [ -x /var/jb/usr/bin/uicache ]; then
    /var/jb/usr/bin/uicache -p /var/jb/Applications/UltraHidePro.app
elif which uicache >/dev/null 2>&1; then
    uicache -p /var/jb/Applications/UltraHidePro.app
fi
exit 0
